# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7k160tffg676-2L
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado/cpu/cpu.cache/wt [current_project]
set_property parent.project_path E:/vivado/cpu/cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/vivado/cpu/cpu.srcs/sources_1/new/add.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/g_p.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/cla2.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/cla4.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/cla8.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/cla16.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/cla32.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/cla_32.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/mux4x32.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/shift.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/addsub32.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/alu.v
  E:/vivado/cpu/cpu.srcs/sources_1/new/cpu_top.v
}
read_xdc E:/vivado/cpu/cpu.srcs/constrs_1/new/cpu_top.xdc
set_property used_in_implementation false [get_files E:/vivado/cpu/cpu.srcs/constrs_1/new/cpu_top.xdc]

catch { write_hwdef -file cpu_top.hwdef }
synth_design -top cpu_top -part xc7k160tffg676-2L
write_checkpoint -noxdef cpu_top.dcp
catch { report_utilization -file cpu_top_utilization_synth.rpt -pb cpu_top_utilization_synth.pb }
